##############################################################################
# 공통 실행 환경 
##############################################################################
# server define
server:
  port: 9009


# spring config 
spring:
  # profile active
  profiles:
    active:
    - local 
  # banner
  banner:
    charset: utf-8
    location: classpath:config/incident-banner.txt

##############################################################################
# local 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: local
  # 기초 데이터 로딩
        
##############################################################################
# dev 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: dev
        
        
##############################################################################
# stage 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: stage
        
##############################################################################
# production 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: production
        
##############################################################################
# mariadb 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: mariadb